"""
WHAT      Reads the LESSON block out of every demo module and writes
          docs/lessons.md from it. Also the one place that knows how to find a
          demo's LESSON, so run.py can mark the free ones in --list.
WHY       The alternative is a hand-written index, and a hand-written index of
          twelve files goes stale on the first edit nobody remembers to mirror.
          The docstring stays the practitioner's view and LESSON stays the
          reader's view; neither is ever copied by hand into the other.
DOMAIN    D2 Claude Code Configuration and Workflows
TRADEOFF  Reading source with `ast` instead of importing it means LESSON must be
          a literal dict of literals - no f-strings, no computed values, no
          constants pulled in from elsewhere. That is a real restriction and it
          is the price of not executing a module to read its metadata.
ALTERNATIVE  importlib and read module.LESSON. One line shorter and it runs the
          demo: several of these files call asyncio.run() at import time, so
          generating the docs would start making model calls.

Makes no model call. Run it after editing any LESSON:
    uv run python -m playground.lessons
"""
from __future__ import annotations

import ast
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent
DOCS = ROOT.parent.parent / "docs" / "lessons.md"

# WHY: the keys are listed in the order they are meant to be read, not
# alphabetically. setup before run before expect before learn is the sequence a
# reader actually needs; a dict's own order would be whatever each author typed.
ORDER = ("domain", "setup", "run", "cost", "expect", "learn")


def path_of(demo: str) -> Path:
    """Map a dotted demo name onto its file, without importing anything."""
    return ROOT.joinpath(*demo.split(".")).with_suffix(".py")


def extract(path: Path) -> dict[str, Any]:
    """Pull LESSON and KNOWN_ISSUE out of a module's source text.

    Only module-level assignments are considered, and only literals. Anything
    computed is skipped in silence rather than guessed at - a half-read LESSON
    would produce a doc row that looks authoritative and is not.
    """
    if not path.exists():
        return {}
    tree = ast.parse(path.read_text(encoding="utf-8"))
    found: dict[str, Any] = {}
    for node in tree.body:
        if not isinstance(node, ast.Assign):
            continue
        for target in node.targets:
            if isinstance(target, ast.Name) and target.id in ("LESSON", "KNOWN_ISSUE"):
                try:
                    found[target.id] = ast.literal_eval(node.value)
                except ValueError:
                    # WHY: a non-literal LESSON is a bug in the demo, not here.
                    # It surfaces as a missing row, which the audit in
                    # docs/status.md is designed to catch.
                    pass
    return found


def is_free(lesson: dict[str, Any] | None) -> bool:
    """True when running this demo spends no quota."""
    # WHY: derived from the LESSON's own cost line rather than a second list of
    # free demos kept somewhere else. Two lists disagree eventually, and the one
    # people trust is always the wrong one.
    return bool(lesson) and str(lesson.get("cost", "")).lower().startswith("free")


def _rows(demos: dict[str, str]) -> list[str]:
    lines = [
        "| Demo | Domain | Cost | Completes here |",
        "|------|--------|------|----------------|",
    ]
    for name in demos:
        data = extract(path_of(name))
        lesson = data.get("LESSON")
        if not lesson:
            lines.append(f"| `{name}` | - | - | **no LESSON block** |")
            continue
        state = "known issue" if data.get("KNOWN_ISSUE") else "yes"
        lines.append(
            f"| [`{name}`](#{name.replace('.', '')}) | {lesson['domain']} "
            f"| {lesson['cost']} | {state} |"
        )
    return lines


def _sections(demos: dict[str, str]) -> list[str]:
    out: list[str] = []
    for name in demos:
        data = extract(path_of(name))
        lesson = data.get("LESSON")
        if not lesson:
            continue
        out += [f"### {name}", ""]
        for key in ORDER:
            if key == "domain":
                continue
            out.append(f"- **{key}** — {lesson[key]}")
        if data.get("KNOWN_ISSUE"):
            out += ["", f"> **KNOWN ISSUE.** {data['KNOWN_ISSUE']}"]
        out.append("")
    return out


def render(demos: dict[str, str]) -> str:
    header = [
        "# Lessons",
        "",
        "Generated by `uv run python -m playground.lessons` from the `LESSON` block at the",
        "top of each demo module. Do not edit this file; edit the module and",
        "regenerate. The module docstrings are deliberately *not* reproduced here —",
        "a docstring argues a tradeoff with a practitioner, a LESSON tells a reader",
        "what to run and what they should see.",
        "",
        "The order below is the reading order, and it is load-bearing.",
        "",
    ]
    body = _rows(demos) + ["", "## Every lesson in full", ""] + _sections(demos)
    return "\n".join(header + body) + "\n"


def main() -> None:
    # WHY: imported inside the function, not at module scope. run.py imports this
    # module to mark the free demos in --list, so a top-level import here would
    # close the cycle and break both files.
    from playground.run import DEMOS

    DOCS.write_text(render(DEMOS), encoding="utf-8")
    missing = [n for n in DEMOS if not extract(path_of(n)).get("LESSON")]
    print(f"wrote {DOCS} ({len(DEMOS)} demos)")
    if missing:
        print(f"WARNING: no LESSON block in {missing}")


if __name__ == "__main__":
    main()
